# Generated by Django 4.2.3 on 2023-07-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0005_category_itemimages_cloth'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='mainImage',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
