# Generated by Django 4.2.3 on 2023-07-19 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0006_cloth_mainimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='imageObject',
        ),
        migrations.AddField(
            model_name='itemimages',
            name='clothObject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop_site.cloth'),
            preserve_default=False,
        ),
    ]
