# Generated by Django 4.2.3 on 2023-07-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0007_remove_cloth_imageobject_itemimages_clothobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
