# Generated by Django 4.2.3 on 2023-07-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0008_cloth_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='brand',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
